$id: https://schemas.dpe-audit.fr/production
$schema: https://json-schema.org/draft/2020-12/schema
title: Production
type: object
properties:
  panneaux_photovoltaiques:
    title: Liste des panneaux photovoltaïques
    type: array
    default: []
    items:
      $ref: /production/panneau_photovoltaique
  data:
    $ref: "#/$defs/data"
required:
  - panneaux_photovoltaiques
$defs:
  data:
    title: Données calculées
    type: object
    readOnly: true
    properties:
      ppv:
        title: Production photovoltaïque en kWh/an
        type: number
